language: php
php:

- "7.0"
- "5.6"

sudo: false

matrix:
    fast_finish: true

install:

- composer install
- composer self-update
- composer update

script:

- vendor/bin/phpunit
- vendor/bin/psalm
